In [1]:
import numpy as np
import pandas as pd
import sklearn.model_selection as sklms
import sklearn.preprocessing as sklpre

In [2]:
df = pd.read_csv("data/ozone_496obs_25vars.txt", header=0, sep=" ")

In [3]:
#variables = df.loc[:, (df.columns != "FFVC") & (df.columns != "SEX")]
#outcome = np.array(df.loc[:,"FFVC"], dtype=float)
variables = df.loc[:,  (df.columns != "SEX")]


onehot_sex = pd.get_dummies(df.loc[:,"SEX"]).set_axis(
    ["MALE", "FEMALE"], axis=1, inplace=False
)

variables = variables.join(onehot_sex)

In [4]:
variables

,ALTER,ADHEU,HOCHOZON,AMATOP,AVATOP,ADEKZ,ARAUCH,AGEBGEW,FSNIGHT,FLGROSS,...,FSPT,FTEH24,FSATEM,FSAUGE,FLGEW,FSPFEI,FSHLAUF,FFVC,MALE,FEMALE
0,8.038330,0,0,0,0,0,1,5050,0,151.7,...,0,22.0,0,0,38,0,0,2.80,0,1
1,8.421629,0,0,0,0,0,1,3800,0,147.5,...,1,22.0,0,0,51,0,0,2.64,1,0
2,8.396988,0,0,1,0,0,0,4980,0,130.9,...,0,22.0,0,0,29,0,0,2.29,1,0
3,7.978097,0,0,0,0,0,0,3300,1,146.0,...,0,21.5,0,0,36,0,1,2.20,0,1
4,7.953457,0,0,0,0,0,1,2550,0,132.5,...,0,22.0,0,0,34,0,0,2.09,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,7.687885,0,0,0,0,0,0,3960,0,135.9,...,1,12.9,0,0,37,0,0,2.28,1,0
492,7.258042,1,0,0,0,0,0,2790,0,134.7,...,1,5.6,0,1,28,0,0,2.19,1,0
493,7.572895,1,0,0,0,0,0,3980,0,131.6,...,0,5.6,0,0,29,0,0,2.22,1,0
494,6.910335,0,0,0,0,0,0,3350,0,126.7,...,0,5.6,0,0,26,0,0,2.16,0,1
495,7.581109,1,0,1,1,0,0,3660,0,131.8,...,1,6.4,0,1,25,0,0,1.92,1,0

In [5]:
variables_train_, variables_test_ = sklms.train_test_split(
    variables, test_size=0.5, stratify=variables["FSATEM"]
)

In [6]:
variables_test_

,ALTER,ADHEU,HOCHOZON,AMATOP,AVATOP,ADEKZ,ARAUCH,AGEBGEW,FSNIGHT,FLGROSS,...,FSPT,FTEH24,FSATEM,FSAUGE,FLGEW,FSPFEI,FSHLAUF,FFVC,MALE,FEMALE
101,8.626968,0,1,0,0,0,0,2810,0,148.2,...,0,19.5,0,0,35,0,0,2.51,0,1
138,7.389459,0,1,0,0,0,0,3980,0,133.6,...,0,21.7,0,0,31,0,0,2.07,0,1
7,7.964408,1,0,0,1,1,0,2880,1,142.9,...,1,22.0,0,1,49,0,0,2.37,0,1
96,8.317591,1,1,0,0,0,1,3350,0,140.9,...,1,19.5,0,1,32,0,0,2.46,1,0
13,8.095825,0,0,1,0,0,0,3100,0,142.2,...,1,22.0,0,0,36,0,1,2.55,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,6.888433,0,0,1,0,0,0,3630,0,137.2,...,0,12.9,0,0,29,0,0,2.59,1,0
290,8.342231,0,1,0,0,0,1,2910,0,145.6,...,0,18.0,0,0,32,0,0,2.01,0,1
341,8.668036,0,1,1,0,0,1,3680,0,144.7,...,0,7.8,0,1,40,0,1,2.28,0,1
451,8.465435,0,0,0,0,0,1,3960,0,139.5,...,0,7.4,0,0,44,0,0,2.30,0,1
243,6.926762,0,1,0,0,0,0,4340,0,144.4,...,0,20.1,0,0,39,0,0,1.97,0,1

In [7]:
# Which columns to scale:
col_continuous = np.array(["ALTER", "AGEBGEW", "FLGROSS", "FNOH24", "FLTOTMED", "FO3H24", "FTEH24", "FLGEW",  "FFVC"])

# Defining the scaler (subtracts mean, divides by standard deviation):
scaler = sklpre.StandardScaler().fit(variables_train_[col_continuous].values)

scaled_cols_train = scaler.transform(variables_train_[col_continuous])
scaled_cols_test = scaler.transform(variables_test_[col_continuous])

In [8]:
scaled_cols_train

array([[ 1.2378645 ,  1.10490866,  1.22768551, ..., -0.57024496,
         0.1167544 ,  0.28295398],
       [ 2.29665149,  0.43916268,  1.43737285, ...,  1.05582005,
         0.51159657,  0.81211466],
       [-1.12438716, -2.3717648 ,  0.41889152, ...,  0.63366856,
        -0.27808776,  0.57693213],
       ...,
       [ 1.36242767, -0.02316092,  1.45235051, ...,  1.18090198,
         0.64321063,  0.16536271],
       [-1.33347535,  1.27134515, -0.56963448, ...,  0.63366856,
        -0.40970182, -1.33392589],
       [-0.45708443,  0.64258506,  0.14929352, ..., -0.0073763 ,
        -0.67292993, -0.65777613]])

In [9]:
feature_names = np.array(variables.columns.values, dtype=str)
feature_names

col_categorical = []
for item in feature_names:
    if item not in col_continuous:
        col_categorical.append(item)


variables_categorical_train = variables_train_.loc[:, col_categorical]
variables_categorical_test = variables_test_.loc[:, col_categorical]

In [10]:
col_continuous

array(['ALTER', 'AGEBGEW', 'FLGROSS', 'FNOH24', 'FLTOTMED', 'FO3H24',
       'FTEH24', 'FLGEW', 'FFVC'], dtype='<U8')

In [11]:
variables_continuous_train = pd.DataFrame(scaled_cols_train, columns=col_continuous)
variables_continuous_test = pd.DataFrame(scaled_cols_test, columns=col_continuous)

In [12]:
variables_categorical_train

,ADHEU,HOCHOZON,AMATOP,AVATOP,ADEKZ,ARAUCH,FSNIGHT,FMILB,FTIER,FPOLL,FSPT,FSATEM,FSAUGE,FSPFEI,FSHLAUF,MALE,FEMALE
471,1,0,1,0,0,0,0,1,0,1,1,0,0,0,0,1,0
312,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1
362,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
188,0,1,0,0,0,0,0,1,0,1,1,0,0,0,0,1,0
161,0,1,0,0,1,1,1,0,0,0,0,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,0,0,0,0,0,0,1,1,0,0,1,1,0,1,1,1,0
189,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
303,1,0,1,0,1,0,0,0,0,1,1,0,1,0,0,1,0
354,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
191,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [13]:
variables_final_train = variables_categorical_train.join(variables_continuous_train) 
variables_final_test = variables_categorical_test.join(variables_continuous_test)

In [14]:
variables_train_array = np.concatenate([variables_categorical_train, variables_continuous_train], axis=1)

variables_final_train = pd.DataFrame(variables_train_array, columns=(list(col_categorical)+list(col_continuous)))

In [15]:
variables_test_array = np.concatenate([variables_categorical_test, variables_continuous_test], axis=1)

variables_final_test = pd.DataFrame(variables_test_array, columns=(list(col_categorical)+list(col_continuous)))

In [16]:
variables_final_test

,ADHEU,HOCHOZON,AMATOP,AVATOP,ADEKZ,ARAUCH,FSNIGHT,FMILB,FTIER,FPOLL,...,FEMALE,ALTER,AGEBGEW,FLGROSS,FNOH24,FLTOTMED,FO3H24,FTEH24,FLGEW,FFVC
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.317941,-1.021780,1.602127,-1.316818,-0.367118,0.258623,0.461681,0.116754,0.665126
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,-0.692865,1.141895,-0.584612,0.955770,-0.367118,1.742308,0.805656,-0.409702,-0.628378
2,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,1.0,0.241359,-0.892329,0.808311,1.910256,-0.367118,1.124106,0.852562,1.959351,0.253556
3,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.815239,-0.023161,0.508758,-1.316818,-0.367118,0.444084,0.461681,-0.278088,0.518137
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.454896,-0.485485,0.703467,1.910256,-0.367118,1.124106,0.852562,0.248368,0.782717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-1.506974,0.494642,-0.045416,0.001283,-0.367118,-1.534164,-0.570245,-0.672930,0.900308
244,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.855278,-0.836850,1.212708,-1.225914,-0.367118,-0.235939,0.227152,-0.278088,-0.804765
245,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.384671,0.587106,1.077909,-0.225976,-0.367118,-1.225063,-1.367642,0.774825,-0.011024
246,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.055468,1.104909,0.299070,-0.316879,-0.367118,-1.225063,-1.430183,1.301281,0.047771
247,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,-1.444692,1.807641,1.032976,-0.953204,-0.367118,0.134982,0.555492,0.643211,-0.922356

In [17]:
variables_final_train

,ADHEU,HOCHOZON,AMATOP,AVATOP,ADEKZ,ARAUCH,FSNIGHT,FMILB,FTIER,FPOLL,...,FEMALE,ALTER,AGEBGEW,FLGROSS,FNOH24,FLTOTMED,FO3H24,FTEH24,FLGEW,FFVC
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.237864,1.104909,1.227686,0.001283,-0.367118,-1.534164,-0.570245,0.116754,0.282954
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,2.296651,0.439163,1.437373,-0.953204,-0.367118,1.278657,1.055820,0.511597,0.812115
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,-1.124387,-2.371765,0.418892,-1.271366,-0.367118,-0.266849,0.633669,-0.278088,0.576932
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,-0.461533,-0.577949,0.523735,-0.225976,-0.367118,-1.503254,-1.195655,-0.146474,0.224158
4,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.366876,-0.134119,0.059428,0.228542,-0.367118,0.660454,0.242788,-0.278088,1.282480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,-0.448187,-0.115626,-0.075371,0.955770,-0.367118,0.505904,0.602398,0.248368,1.958629
244,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,-0.105638,-0.522470,-0.374925,-0.225976,2.161915,-1.503254,-1.195655,-0.804544,-0.598980
245,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.362428,-0.023161,1.452351,1.001221,-0.367118,0.969556,1.180902,0.643211,0.165363
246,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,-1.333475,1.271345,-0.569634,-1.271366,-0.367118,-0.266849,0.633669,-0.409702,-1.333926
247,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,-0.457084,0.642585,0.149294,0.501252,-0.367118,-0.390489,-0.007376,-0.672930,-0.657776

In [18]:
variables_final_train.to_csv("data/ozone_train.csv", index=False)
variables_final_test.to_csv("data/ozone_test.csv", index=False)